compilers:
  - compiler:
      spec: gcc@=11.2.0
      modules:
        - PrgEnv-gnu
        - gcc/11.2.0
        - xpmem
        - libfabric
        - craype-x86-rome
        - craype-network-ofi
      
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: x86_64
      environment: {}
      extra_rpaths: []
  
  - compiler:
        spec: gcc@=10.3.0
        modules:
          - PrgEnv-gnu
          - gcc/10.3.0
          - xpmem
          - libfabric
          - craype-x86-rome
          - craype-network-ofi
      
        paths:
          cc: cc
          cxx: CC
          f77: ftn
          fc: ftn
        flags: {}
        operating_system: sles15
        target: x86_64
        environment: {}
        extra_rpaths: []

  - compiler:
      spec: cce@=15.0.0
      modules:
        - PrgEnv-cray
        - cce/15.0.0
        - xpmem
        - libfabric
        - craype-x86-rome
        - craype-network-ofi
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: x86_64
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: aocc@=4.0.0
      modules:
      - PrgEnv-aocc
      - aocc/4.0.0
      - xpmem
      - libfabric
      - craype-x86-rome
      - craype-network-ofi

      paths:
        cc: cc
        cxx: CC
        f77: None
        fc: None
      flags: {}
      operating_system: sles15
      target: x86_64
      environment: {}
      extra_rpaths: []
 
  - compiler:
      spec: gcc@=7.5.0
      modules: []
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: None
        fc: None
      flags: {}
      operating_system: sles15
      target: x86_64
      environment: {}
      extra_rpaths: []


